// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwvxufnntlytvtqpzbqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dnh1Zm5udGx5dHZ0cXB6YnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODQ5OTYsImV4cCI6MjA3MTE2MDk5Nn0.3GE_GmHJBeiQ-HTGmMvk4c1KIqqIH9MuewPLFyKi5wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});